version: '3.0'

services:
  client:
    container_name: client
    volumes:
      - /social/node_modules
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    command: npx webpack-dev-server --hot --host 0.0.0.0 --port 3000
    restart: always
  server:
    container_name: server
    build:
      dockerfile: json-server/Dockerfile
    volumes:
      - /social/node_modules
    ports:
      - 8000:8000
    command: node ./json-server/index.js
    depends_on:
      - client
    restart: always
