name: linting, testing, building
run-name: 🚀 CI 🚀
on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ master ]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 17.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.mode-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.mode-version }}
      - name: install modules
        run: npm install --legacy-peer-deps
      - name: build production project
        run: npm run build:prod
        if: always()
      - name: linting TypeScript
        run: npm run lint:ts
        if: always()
      - name: linting SCSS
        run: npm run lint:scss
        if: always()
      - name: unit testing
        run: npm run test:unit
        if: always()
      - name: build storybook
        run: npm run storybook:build
        if: always()
      - name: screenshot testing
        run: npm run test:ui:ci
        if: always()
